### ISSUE TITLE
Array uniforms?

### ISSUE THREAD

**Issue by nedtwigg** [xemantic/shader-web-background#7]
My shader has:

```glsl
uniform vec2 iThingsPos[8];
```

And in the js I do:

```typescript
    shaderWebBackground.shade({
      canvas: ref.current!,
      shaders: {
        image: {
          uniforms: {
            iThingsPos: (gl, loc, ctx) => gl.uniform2fv(loc, new Float32(...))
          },
        },
      },
    });
```

I'm getting this runtime error

> shaderWebBackground.ConfigError: No configuration for uniform "iThingsPos[0]" defined in shader "image"

Is there a trick for passing array uniforms with this library?

Thanks for open sourcing this btw, great little library!

**Comment by morisil** [comment]
I took a loot at the code and I see where the problem is. It seems that array uniforms are resolved in a particular way by WebGL. I will have no time to fix it in a near feature. Also I have been working on the second version of this library, which is completely changing and simplifies the way uniforms are provisioned. So I would rather release this new version instead of fixing it in the old one.

**Comment by nedtwigg** [comment]
Thanks for looking! Do you mind pointing me towards the problem, maybe I can hack something together? I'm hoping to ship a little demo with this over the weekend.

**Comment by morisil** [comment]
Here uniform specification is being obtained from the shader GLSL code after compilation:
https://github.com/xemantic/shader-web-background/blob/main/src/main/js/webgl-utils.js#L270

Here it is being matched with uniforms provided in shader configuration:
https://github.com/xemantic/shader-web-background/blob/main/src/main/js/shader-web-background.js#L324

I assume that your error means that array uniforms are being reported with `[0]` suffix in WebGL after doing:
```
gl.getActiveUniform(...)
```
Maybe naming the uniform in shader configuration with such a suffix would fix the issue automatically?

```
shaderWebBackground.shade({
      canvas: ref.current!,
      shaders: {
        image: {
          uniforms: {
            iThingsPos[0]: (gl, loc, ctx) => gl.uniform2fv(loc, new Float32(...))
          },
        },
      },
    });
```

Very sub-optimal and I am not even sure if it is allowed in JavaScript, but you can give it a try. A more elegant solution would be to detect uniforms suffixed with `[0]` and add something like a boolean `isArray` flag to UniformSpec.

**Comment by nedtwigg** [comment]
Wow, thanks a ton! Using this works great:

```js
        image: {
          uniforms: {
            iTime: (gl: any, loc: any) => gl.uniform1f(loc, performance.now() / 1000),
            iResolution: (gl, loc, ctx) => gl.uniform2f(loc, ctx.width, ctx.height),
            "iThingsPos[0]": (gl, loc, ctx) => gl.uniform2fv(loc, ...),
            "iThingsWidth[0]": (gl, loc, ctx) => gl.uniform1fv(loc, ...)
          },
```

I tested with array lengths 1, 2, 3, and 4, and every time it worked great. I would submit a PR but your project is perfect for my needs as-is, thanks again!

**Comment by morisil** [comment]
Amazing! @nedtwigg please let me know when/if I can see your project online, I am very curious.

**Comment by nedtwigg** [comment]
We were able to show it to some friends this weekend thanks to your help, and as a result it's back to the drawing board. I'll definitely post back here when it ships for real, maybe a week from now.
